### ISSUE TITLE
using return bool + fallback functions

### ISSUE THREAD

**Issue by rstormsf** [jbaylina/eip820#5]
https://github.com/jbaylina/eip820/blob/master/contracts/ExampleImplementer.sol#L5
```
pragma solidity ^0.4.18;

contract ExampleImplementer {
    function canImplementInterfaceForAddress(address addr, bytes32 interfaceHash) view public returns(bool) {
        return true;
    }
}
```

If I unlock the fallback function and provide some default behavior, then it would break those checks because of strange behavior by design in solidity if a method does not exist it will instead execute the fallback function, and if the fallback function does not raise an exception it will return 1 causing the check to pass.

The only solution that comes to my mind is to use some magic numbers.  Maybe we should return uint which should be more than 0.

**Comment by jacquesd** [comment]
@rstormsf nice catch.
> This was actually closed in 78eb6fa62f942b36983be31772874b320415aea0.
