### ISSUE TITLE
setInterfaceImplementer should fail if implemented with 165

### ISSUE THREAD

**Issue by fulldecent** [jbaylina/eip820#7]
The function `setInterfaceImplementer` should fail if the interface is currently implemented as a ERC165 interface.

This is for backward compatibility. And also it is an implementation detail with how 820 cache currently works.

**Comment by jacquesd** [comment]
@fulldecent thanks for the issue. This was actually closed in 225041f707c83cb976ce8c314762ac8ff783ead1.
